/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutletsRouteImport } from './routes/outlets'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as MapRouteImport } from './routes/map'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutletsIndexRouteImport } from './routes/outlets.index'
import { Route as OutletsIdRouteImport } from './routes/outlets.$id'

const OutletsRoute = OutletsRouteImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletsIndexRoute = OutletsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutletsRoute,
} as any)
const OutletsIdRoute = OutletsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OutletsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/evaluation': typeof EvaluationRoute
  '/map': typeof MapRoute
  '/monitoring': typeof MonitoringRoute
  '/outlets': typeof OutletsRouteWithChildren
  '/outlets/$id': typeof OutletsIdRoute
  '/outlets/': typeof OutletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/evaluation': typeof EvaluationRoute
  '/map': typeof MapRoute
  '/monitoring': typeof MonitoringRoute
  '/outlets/$id': typeof OutletsIdRoute
  '/outlets': typeof OutletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/evaluation': typeof EvaluationRoute
  '/map': typeof MapRoute
  '/monitoring': typeof MonitoringRoute
  '/outlets': typeof OutletsRouteWithChildren
  '/outlets/$id': typeof OutletsIdRoute
  '/outlets/': typeof OutletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/evaluation'
    | '/map'
    | '/monitoring'
    | '/outlets'
    | '/outlets/$id'
    | '/outlets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/evaluation'
    | '/map'
    | '/monitoring'
    | '/outlets/$id'
    | '/outlets'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/evaluation'
    | '/map'
    | '/monitoring'
    | '/outlets'
    | '/outlets/$id'
    | '/outlets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  EvaluationRoute: typeof EvaluationRoute
  MapRoute: typeof MapRoute
  MonitoringRoute: typeof MonitoringRoute
  OutletsRoute: typeof OutletsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outlets': {
      id: '/outlets'
      path: '/outlets'
      fullPath: '/outlets'
      preLoaderRoute: typeof OutletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets/': {
      id: '/outlets/'
      path: '/'
      fullPath: '/outlets/'
      preLoaderRoute: typeof OutletsIndexRouteImport
      parentRoute: typeof OutletsRoute
    }
    '/outlets/$id': {
      id: '/outlets/$id'
      path: '/$id'
      fullPath: '/outlets/$id'
      preLoaderRoute: typeof OutletsIdRouteImport
      parentRoute: typeof OutletsRoute
    }
  }
}

interface OutletsRouteChildren {
  OutletsIdRoute: typeof OutletsIdRoute
  OutletsIndexRoute: typeof OutletsIndexRoute
}

const OutletsRouteChildren: OutletsRouteChildren = {
  OutletsIdRoute: OutletsIdRoute,
  OutletsIndexRoute: OutletsIndexRoute,
}

const OutletsRouteWithChildren =
  OutletsRoute._addFileChildren(OutletsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  EvaluationRoute: EvaluationRoute,
  MapRoute: MapRoute,
  MonitoringRoute: MonitoringRoute,
  OutletsRoute: OutletsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
